stages:
  - sync

sync_from_github:
  stage: sync
  script:
    - echo "开始从 GitHub 同步代码..."
    - git config --global user.name "GitLab Sync Bot"
    - git config --global user.email "gitlab-bot@example.com"
    - git remote add github https://github.com/zitzhen/CoCo-Community.git || true
    - git fetch github
    - git checkout main
    - git reset --hard github/main
    - git push origin main --force
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"  # 仅允许手动触发