name: CoudflareD1-control

on:
  push:
    branches:
      'public/control/***'  # 监听 control 目录下的文件变化

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0