name: CoudflareD1-control

on:
  push:
    branches:
      'public/control/***'  # 监听 control 目录下的文件变化

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: List subdirectories in ./src
        run: |
          echo "控件列表："
          for dir in ./public/control/*/; do
            name=$(basename "$dir")
            
            # 忽略的目录列表（用空格分隔）
            ignore_list=".github "

            # 判断是否在忽略列表中
            if [[ " $ignore_list " == *" $name "* ]]; then
              continue
            fi

            echo "$name"
          done