name: Generate Sitemap
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate base sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: "https://cc.zitzhen.cn"
          exclude-paths: "404.html,google46eebdeb664df7df.html,baidu_verify_codeva-Nc3ckBEoE0.html,control/css,control/js,user"
          disable-indexes: true

      - name: Add control subdirectories
        run: |
          # 扫描control目录下的一级子目录（排除css/js）
          find control -maxdepth 1 -mindepth 1 -type d \
            -not -name "css" -not -name "js" | while read dir; do
            # 将目录路径转换为URL格式
            url_path="https://cc.zitzhen.cn/${dir}/"
            # 将URL插入到sitemap.xml的<urlset>标签前
            sed -i "/<\/urlset>/i \ \ <url>\n\ \ \ \ <loc>${url_path//\//\\/}<\/loc>\n\ \ <\/url>" sitemap.xml
          done

      - name: Add user information pages
        run: |
          # 扫描user/information目录下的JSON文件（排除example.json）
          find user/information -type f -name "*.json" ! -name "example.json" | while read file; do
            # 提取纯文件名（不含路径和扩展名）
            filename=$(basename "$file" .json)
            # 构建URL并插入sitemap
            url="https://cc.zitzhen.cn/user/$filename"
            # 使用特殊分隔符避免路径转义问题
            sed -i "\|</urlset>|i \ \ <url>\n\ \ \ \ <loc>$url</loc>\n\ \ </url>" sitemap.xml
          done

      - name: Validate sitemap
        run: |
          echo "=== Sitemap Content ==="
          cat sitemap.xml
          echo "=== Control Paths Added ==="
          grep -oP '<loc>\Khttps://cc.zitzhen.cn/control/[^<]+' sitemap.xml
          echo "=== User Paths Added ==="
          grep -oP '<loc>\Khttps://cc.zitzhen.cn/user/[^<]+' sitemap.xml
          echo "=== Excluded URLs Check ==="
          ! grep -q 'https://cc.zitzhen.cn/user/example' sitemap.xml && echo "✅ example.json excluded" || echo "❌ example.json found in sitemap"
          ! grep -q 'https://cc.zitzhen.cn/user/' sitemap.xml && echo "✅ /user/ directory excluded" || echo "❌ /user/ directory found in sitemap"

      - name: Set git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Update sitemap"
          title: "Update sitemap"
          body: "自动生成并更新 sitemap.xml"
          branch: "auto/update-sitemap-${{ github.run_id }}"
          base: main
          add-paths: sitemap.xml
          delete-branch: true